org.gradle.jvmargs=-Xmx2G

# BTA
bta_version=7.3_04
bta_channel=release

# Loader
loader_version=0.15.6-bta.7

# Other Mods
mod_menu_version=3.0.0
halplibe_version=5.3.1
catalystcore_version=2.2.0
catalysteffects_version=2.5.1
btwaila_version=1.2.2-7.3_04
uselessnumerical_version=1.1.0

# Mod
mod_version=0.12.2+7.3_04
mod_group=teamport
mod_name=better-with-aether