#Minecraft server properties
#Wed Oct 22 18:06:46 CDT 2025
default-gamemode=survival
view-distance=10
language=en_US
uuid-service=https\://api.minecraftservices.com/minecraft/profile/lookup/name/%s
server-ip=192.168.1.115
stats-token=only-enter-a-value-if-you-are-a-registered-server
forceSaveAllChunksOnAutosave=false
level-seed=
allow-nether=true
server-port=25565
sleep-percentage=0
autosaveInterval=5
login-timeout-time=90000
world-type=minecraft\:overworld.extended
join-message=
allow-paradise=false
level-name=world
motd=A Better than Adventure\! Server
white-list=false
pvp=true
enable-item-clumping=true
spawn-animals=true
difficulty=2
disable-photomode=false
spawn-monsters=true
summon-limit=10
max-players=20
maxChunksSavedPerAutosave=24
spawn-protection=0
online-mode=false
packet-delay=1
allow-flight=false
