name: Update manifest.json

on:
  workflow_dispatch:
  
  push:
    branches:
      - "7.3"
    paths:
      - "remoteAssets/**/*"

jobs:
  build:
    name: update resource manifest
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: remoteAssets

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Setup UV
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --script .generateManifest.py

      - name: Remove old file
        run: rm -f manifest.json

      - name: Generate new manifest
        run: uv run --script .generateManifest.py

      - name: Commit manifest
        run: |
          git config --global user.name 'Father Sentry'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Update remoteAssets/manifest.json"
          git push
